export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_FAIL = 'FETCH_CURRENCIES_START';

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REM_FAVOURITE = 'REM_FAVOURITE';